url: "https://www.kodehalloej.dk"
title: "Kodehalløj"

plugins:
  - jekyll-postcss
  - jekyll-minifier
  - jekyll_picture_tag

postcss:
  cache: false

jekyll-minifier:
  compress_css: false

picture:
  source: "assets/img"
  output: "assets/img/_generated"

exclude:
  - assets/js/encode.js
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js
