url: "https://www.kodehalloej.dk"
title: "Kodehalløj"

plugins:
  - jekyll-postcss
  - jekyll-minifier

postcss:
  cache: false

jekyll-minifier:
  compress_css: false

exclude:
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js
